/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Clip = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'voiceoverScript' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'createClip' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Clip], []),
  'deleteClip' : IDL.Func([IDL.Text], [], []),
  'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
  'getClip' : IDL.Func([IDL.Text], [Clip], ['query']),
  'updateClipContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Clip = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'voiceoverScript' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'createClip' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Clip], []),
    'deleteClip' : IDL.Func([IDL.Text], [], []),
    'getAllClips' : IDL.Func([], [IDL.Vec(Clip)], ['query']),
    'getClip' : IDL.Func([IDL.Text], [Clip], ['query']),
    'updateClipContent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };